#!/bin/bash

# Estimate an N-gram kneser-ney language model from the raw text files.


cp="berkeleylm-1.1.5/src"
N=3

#in_file="Data/ham_ngram_upper_words"
#out_file="ham_ngram_upper_words.arpa"
#java -ea -mx1000m -server -cp $cp edu.berkeley.nlp.lm.io.MakeKneserNeyArpaFromText $N $out_file $in_file
#exit

types=(ngram_upper_words ngram_lower_words ngram_upper_chars ngram_lower_chars)
classes=(ham spam)
for t in ${types[*]}
do
    for class in ${classes[*]}
    do
        model="$class"_"$t"
        in_file="Data/$model"
        out_file="Models/N_"$N"_$model.arpa"
        echo "Generating $out_file..."
        java -ea -mx1000m -server -cp $cp edu.berkeley.nlp.lm.io.MakeKneserNeyArpaFromText $N $out_file $in_file
    done
done
