#!/bin/bash

# A script that calls all of the other scripts in order to do the all of
# the preprocessing and model generation steps.
#
# Make sure all of the individual scripts work before using this one.



# Steps are enumerated according the REAMDE.md:

# 3. Preprocess first 60000 emails for filtered training bag-of-words set.
echo "Generating bulk training data."
python preprocess.py trec07p 1 60000 Data/train_bulk.arff -stopwords stopwords.txt

# 4. Preprocess last 15419emails for filtered testing bag-of-words set.
echo "Generating bulk testing data."
python preprocess.py trec07p 60001 75419 Data/test_bulk.arff -stopwords stopwords.txt

exit
# TODO - should we append n-gram and other features at step 3 and 4??

# 5. Convert batch sets to standardized .arff files for Weka.
echo "Converting bulk data to standardized data."
./convert

# 6. Generate the n-gram preprocessed data files.
echo "Generating n-gram training data files."
./generate_ngram_files

# 7. Build the n-gram models using the Berkley LM tool.
echo "Generating n-gram models."
./build_ngram_models
