#!/bin/bash


split_type=$1
outfile=$2

if [ -z "${split_type}" ] | [ -z "${outfile}" ]; then
    echo "Usage: ./do_ngram_to_weka <split type> <out name>"
    echo "e.g. ./do_ngram_to_weka 60_30_10 combo_all"
    exit
fi


# TODO - param
bulk_fname="BoW_meta_bulk"


split_81_9_10() {
    train_start=61090
    train_end=67877
    test_start=67878
    test_end=75419
    split="Split_81_9_10"
}

split_60_30_10() {
    train_start=45253
    train_end=67877
    test_start=67878
    test_end=75419
    split="Split_60_30_10"
}


split_$split_type
offset=$train_start


echo "Converting training data..."
python ngram_to_weka.py trec07p Models/$split/Evaluations $train_start $train_end config Data/$split/${outfile}_bulk_train.arff --offset $offset --length-file Data/lengths.txt --real-probs --BoW-file Data/$split/${bulk_fname}_train.arff

echo "Converting test data..."
python ngram_to_weka.py trec07p Models/$split/Evaluations $test_start $test_end config Data/$split/${outfile}_bulk_test.arff --offset $offset --length-file Data/lengths.txt --real-probs --BoW-file Data/$split/${bulk_fname}_test.arff
