#!/bin/bash

# Generates all possible data sets for the N-Gram training sets:
#   {regular words, lowercase words, regular characters, lowercase characters}
# Each iteration will produce two files: one for spam messages and another
# for ham messages, prefaced with "spam_" and "ham_", respectively.
# e.g. the first line will produce the following two files:
#   spam_ngram_upper_words
#   ham_ngram_upper_words


# <<< DATA RANGE >>>
# Training and testing data ranges:

split_81_9_10() {
    # first 81% of data
    ng_train_start=1
    ng_train_end=61089
    # next 9% of data
    ng_eval_start=61090
    ng_eval_end=67877
    # last 10% of data
    test_start=67878
    test_end=75419
}

split_60_30_10() {
    # first 60% of data
    ng_train_start=1
    ng_train_end=45252
    # next 30% of data
    ng_eval_start=45253
    ng_eval_end=67877
    # last 10% of data
    test_start=67878
    test_end=75419
}

split_60_30_10
#split_81_9_10
# <<< DATA RANGE >>>


train_dir="Data/NGramTrain/Split_60_30_10"
test_dir="Data/NGramTest"
cmd="python preprocess.py trec07p"


# If stopwords are enabled, add that parameter
if [ "$2" = "stopwords" ]; then
    echo "Using STOPWORDS."
    train_dir="${train_dir}/StopwordsRemoved"
    test_dir="${test_dir}/StopwordsRemoved"
    sw_param="-stopwords stopwords.txt"
else
    sw_param=""
fi


# Make all necessary directories if they don't already exist
mkdir -p $train_dir/lower_chars
mkdir -p $train_dir/lower_words
mkdir -p $train_dir/upper_chars
mkdir -p $train_dir/upper_words
mkdir -p $test_dir/lower_chars
mkdir -p $test_dir/lower_words
mkdir -p $test_dir/upper_chars
mkdir -p $test_dir/upper_words


# Run the preprocessor on all of the data
if [ -z "${1}" ] || [ "$1" -eq "1" ]; then
    echo "Preprocessing N-Gram TRAIN data."
    $cmd $ng_train_start $ng_train_end $train_dir --ngrams --ngram-all $sw_param
fi
if [ -z "${1}" ] || [ "$1" -eq "2" ]; then
    echo "Preprocessing N-Gram EVAL data."
    $cmd $ng_eval_start $ng_eval_end $train_dir --ngrams --ngram-all --ngram-test $sw_param
fi
if [ -z "${1}" ] || [ "$1" -eq "3" ]; then
    echo "Preprocessing N-Gram TEST data."
    $cmd $test_start $test_end $test_dir --ngrams --ngram-all --ngram-test $sw_param
fi


echo "All done. SUCCESS!"
