#!/bin/bash

path="/scratch/cluster/teammco/CS388L_Proj"

in="$path/sample_data/text.arff"
out="$path/sample_data/text_pre.arff"
classifier="weka.filters.unsupervised.attribute.StringToWordVector"

cp_weka="$path/weka-3-6-12/weka.jar"
cp_proj="$path"

# -C word counts
# -L lower case
java -Xmx1024m -cp "$cp_weka:$cp_proj" $classifier -C -L -i $in -o $out
