#!/bin/bash

path="/scratch/cluster/teammco/CS388L_Proj"

cp_weka="$path/weka-3-6-12/weka.jar"
cp_proj="$path"


train_data="$path/Data/train_std.arff"
test_data="$path/Data/test_std.arff"


#classifier="weka.classifiers.rules.ZeroR"
classifier="weka.classifiers.bayes.NaiveBayes"
#classifier="weka.classifiers.functions.SMO""


java -Xmx1024m -cp "$cp_weka:$cp_proj" $classifier -c 1 -t $train_data -T $test_data
