#!/bin/bash

path="/scratch/cluster/teammco/CS388L_Proj"

train_data="$path/Data/train_bulk.arff"
test_data="$path/Data/test_bulk.arff"
classifier="weka.filters.unsupervised.attribute.StringToWordVector"

cp_weka="$path/weka-3-6-12/weka.jar"
cp_proj="$path"

java -Xmx1024m -cp "$cp_weka:$cp_proj" $classifier -C -L -b -i $train_data -o $path/Data/train_std.arff -r $test_data -s $path/Data/test_std.arff
