import sys

# Converts a data file to an NGram.


def arff_to_ngram(arff_fname, chars = False):
    """
    Reads a bulk ARFF file (generated by preprocess.py) and converts it into
    separate lists of HAM or SPAM.
    """
    arff_file = open(arff_fname, 'r')
    lines = arff_file.readlines()
    lines = map(str.strip, lines)
    if chars:
        lines = map(list, lines)
    else:
        lines = map(str.split, lines)
    print lines


if __name__ == '__main__':
    if len(sys.argv) < 2:
        print 'bye'
        exit(0)
    arff_fname = sys.argv[1]
    print arff_fname
    arff_to_ngram(arff_fname)
    arff_to_ngram(arff_fname, True)
